### PR TITLE
Click to Tweet

### LINKED ISSUE #6: Add click to tweet functionality
- There should be a Twitter icon that allows visitors to click to tweet the quote that appears.

### PR DESCRIPTION
**Pull request by metalandcoffee**
Resolves #6 

I have a few smaller tweaks to make but I wanted to get this out there for first review :)

### CODE REVIEW

**Comment by metalandcoffee** [comment]
I'm pretty confident with these commits so far so I'm ready for any feedback! Please feel free to let me know what changes I need to make and how I can do better! And also feel free to make any changes yourself <3

**Comment by metalandcoffee** [comment]
image

**Comment by M0nica** [comment]
This looks great to me, thanks @metalandcoffee!

**Comment by M0nica** [comment]
@all-contributors please add metalandcoffee for code

**Pull request merged**
