### PR TITLE
fix(src): swap filename for readme link - I39

### PR DESCRIPTION
**Pull request by irmerk**
# Issue #39 

This only swaps filenames to be consistent in the `README`

### CODE REVIEW

**Comment by M0nica** [comment]
@all-contributors add @irmerk for doc contribution

**Comment by M0nica** [comment]
@all-contributors add @irmerk for doc contribution

**Comment by irmerk** [comment]
@M0nica are you able to label mark this as Hacktoberfest?

**Comment by M0nica** [comment]
@irmerk I added hacktoberfest label but it should count towards hacktoberfest here https://hacktoberfest.digitalocean.com/profile with or without the label. I have some contributions that appear for PR that didn't have the label.

**Pull request merged**
